version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: dockerfile.ganache
    expose: 
    - "8545"
    ports:
      - "8545:8545"

  truffle:
    build:
      context: .
      dockerfile: dockerfile.truffle
    depends_on:
      - ganache
    volumes:
      - ./client/src/abi:/app/build/
