FROM nginx:alpine

COPY config/block-explorer-light/dist /usr/share/nginx/html
RUN sed -i 's@NODE_ENV:"production",BASE_URL:"/"@NODE_URL:"/rpcnode/jsonrpc",CONNECTION_TYPE:"json_rpc"@g' /usr/share/nginx/html/js/*.js
COPY config/block-explorer-light/default.nginx /etc/nginx/conf.d/default.conf
