---
version: '3.6'




x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
    - 9545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  environment:
    - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      CONSENSUS_ARGS="--istanbul.blockperiod 5 --mine --minerthreads 1 --miner.gasprice 0 --emitcheckpoints"
      if [ "raft" == $$QUORUM_CONSENSUS ];
      then
        CONSENSUS_ARGS="--raft --raftblocktime 300 --raftport 53000"
      fi

      mkdir -p /config /data /var/log/quorum/;
      cp /quorum/passwords.txt /config/passwords.txt
      cp /quorum/$${QUORUM_CONS_ALGO:-istanbul}Genesis.json /config/genesis.json
      cp -r /quorum/* /data;
      geth --datadir=/data init /config/genesis.json;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth \
      --datadir /data \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --port 30303 \
      --identity node$${NODE_ID}-$$QUORUM_CONSENSUS \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log


x-quorum-member-def:
  &quorum-member-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
    - 9545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  environment:
    - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      
      for i in $$(seq 1 100)
      do
        set -e
        if [ "I'm up!" == "$$(wget --timeout 10 -qO- --proxy off 172.16.239.2$${NODE_ID}:9000/upcheck)" ];
          then break
        else
          echo "Waiting for Tessera..."
          sleep 10
        fi
      done
      

      CONSENSUS_ARGS="--istanbul.blockperiod 5 --mine --minerthreads 1 --miner.gasprice 0 --emitcheckpoints"
      if [ "raft" == $$QUORUM_CONSENSUS ];
      then
        CONSENSUS_ARGS="--raft --raftblocktime 300 --raftport 53000"
      fi

      mkdir -p /config /data/dd /var/log/quorum/;
      cp /quorum/passwords.txt /config/passwords.txt
      cp /quorum/$${QUORUM_CONS_ALGO:-istanbul}Genesis.json /config/genesis.json
      cp -r /quorum/* /data/dd/;
      geth --datadir=/data/dd init /config/genesis.json;
      cp /config/keys/accountkey /data/dd/keystore/key;
      cp /config/keys/nodekey /data/dd/geth/nodekey;
      geth \
      --datadir /data/dd \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --port 30303 \
      --identity node$${NODE_ID}-$$QUORUM_CONSENSUS \
      --ptm.timeout 5 --ptm.url $${QUORUM_PTM_URL} --ptm.http.writebuffersize 4096 --ptm.http.readbuffersize 4096 --ptm.tls.mode off \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$(hostname -i).log




x-tessera-def:
  &tessera-def
  image: quorumengineering/tessera:${QUORUM_TESSERA_VERSION:-0.10.5}
  expose:
    - 9000
    - 9080
    - 9101
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /var/log/tessera/;
      mkdir -p /data/tm/;
      cp /config/keys/tm.* /data/tm/ ;

          cat <<EOF > /data/tm/tessera-config-09.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./data/tm/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9080",
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9101",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9000",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://member1tessera:9000"
               },
               {
                   "url": "http://member2tessera:9000"
               },
               {
                   "url": "http://member3tessera:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat /data/tm/tm.key),
                  "publicKey": "$$(cat /data/tm/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF
          cat /data/tm/tessera-config-09.json
          /tessera/bin/tessera -configfile /data/tm/tessera-config-09.json &> /var/log/tessera/tessera-$$HOSTNAME.log | tee -a /var/log/tessera/tessera-$$HOSTNAME.log



x-cakeshop-def:
  &cakeshop-def
  image: quorumengineering/cakeshop:${QUORUM_CAKESHOP_VERSION:-0.11.0}
  expose:
    - 8999
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      rm -rf /qdata/cakeshop/local
      mkdir -p /qdata/cakeshop/local
      cp /quorum/application.properties /qdata/cakeshop/local/application.properties

      cp /quorum/8nodes_quorum_docker.json /qdata/cakeshop/local/cakeshop.json

      java -Xms128M -Xmx128M -Dspring.config.additional-location=file:/qdata/cakeshop/local/ -Dcakeshop.config.dir=/qdata/cakeshop -jar /cakeshop/cakeshop.war
      ;;






services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator1:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator2:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=3
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 22004:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator4:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *quorum-def
    container_name: rpcnode
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15


  member1tessera:
    << : *tessera-def
    ports:
      - 9081:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=6
    volumes:
      - ./config/nodes/member1:/config/keys
      - member1volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.26

  member1quorum:
    << : *quorum-member-def
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member1tessera
    environment:
      - NODE_ID=6
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member1tessera:9101
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member1:/config/keys
      - member1volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  member2tessera:
    << : *tessera-def
    ports:
      - 9082:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=7
    volumes:
      - ./config/nodes/member2:/config/keys
      - member2volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.27

  member2quorum:
    << : *quorum-member-def
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member2tessera
    environment:
      - NODE_ID=7
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member2tessera:9101
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member2:/config/keys
      - member2volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  member3tessera:
    << : *tessera-def
    ports:
      - 9083:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=8
    volumes:
      - ./config/nodes/member3:/config/keys
      - member3volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.28

  member3quorum:
    << : *quorum-member-def
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member3tessera
    environment:
      - NODE_ID=8
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member3tessera:9101
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member3:/config/keys
      - member3volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18




  cakeshop:
    << : *cakeshop-def
    hostname: cakeshop
    ports:
      - "8999:8999"
    volumes:
      - cakeshop:/data
      - ./config/cakeshop:/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.30

  explorer:
    build: block-explorer-light
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31



  truffle:
    build:
      context: .
      dockerfile: dockerfile.truffle
    depends_on:
      - member1quorum
      - member2quorum
      - member3quorum
    volumes:
      - ./dapp/src/abi:/app/build/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.51

        
  react:
    #profiles: ["dapp"]
    build: 
      context: dapp/.
      dockerfile: dockerfile.react
    volumes:
      - ./dapp/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - truffle
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.61
    


networks:
  quorum-dev-quickstart:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  cakeshop:
  member1volume:
  member2volume:
  member3volume:
  ethlogger:
