FROM node:alpine

WORKDIR /app

COPY ./package.json .
COPY ./truffle-config.js .
COPY contracts ./contracts/
COPY ./migrations ./migrations/

RUN npm i
# RUN npm install -g truffle
RUN npm install -g truffle@5.1.65

# RUN npm i @truffle/hdwallet-provider

#RUN truffle compile

CMD ["truffle", "migrate", "--network", "development", "--reset"]
