FROM node:alpine

WORKDIR /app

COPY ./package.json .
COPY ./truffle-config.js .
COPY contracts ./contracts/
COPY migrations ./migrations/
COPY test ./test/

RUN npm i
RUN npm install -g truffle@5.1.65
RUN truffle migrate --network quorum --reset

CMD ["truffle", "test", "--network", "quorum"]