version: '3.6'

services:
  trufflemigrate:
    profiles: ["trufflemigrate"]
    build:
      context: .
      dockerfile: dockerfile.trufflemigrate
    volumes:
      - ../dapp/src/abi:/app/build/
    network_mode: "host"

  truffletest:
    profiles: ["truffletest"]
    build:
      context: .
      dockerfile: dockerfile.truffletest
    volumes:
      - ../dapp/src/abi:/app/build/
    network_mode: "host"
  